# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OptQ9HZgHkQ8lJTo07u_p2VEar3vrYg4
"""

# Install required libraries
!pip install -q gradio pillow wikipedia torch torchvision requests

import gradio as gr
from PIL import Image
import wikipedia
import random
import requests
from io import BytesIO
import torch
from torchvision import models, transforms

# ======================
# 🌍 GLOBAL RECIPE DATABASE
# ======================
WORLD_RECIPES = {
    # Indian Cuisine
    "biryani": {
        "history": "Brought to India by Mughal emperors from Persia, biryani evolved into regional varieties across the subcontinent. The Hyderabadi version developed in the kitchens of the Nizams, while the Kolkata variant includes potatoes due to wartime rice shortages.",
        "description": "Fragrant layered rice dish cooked with spices, meat, and saffron",
        "ingredients": {
            "Rice": ["2 cups basmati rice", "1 tsp salt", "1 bay leaf", "4 cups water"],
            "Meat": ["500g chicken (bone-in)", "1 cup yogurt", "2 tbsp ginger-garlic paste"],
            "Spices": ["1 tsp garam masala", "1/2 tsp turmeric", "1 tsp red chili powder"],
            "Aromatics": ["2 onions (sliced)", "1/4 cup mint leaves", "1/4 cup coriander leaves"],
            "Other": ["4 tbsp ghee", "Pinch of saffron in 1/4 cup milk"]
        },
        "steps": [
            "Soak rice for 30 minutes, then parboil with whole spices",
            "Marinate chicken with yogurt and spices for 2 hours",
            "Fry onions until golden brown",
            "Layer rice, chicken, fried onions, and herbs in pot",
            "Seal with dough and cook on low heat for 25 minutes (dum cooking)",
            "Let rest for 10 minutes before serving with raita"
        ],
        "image_url": "https://www.licious.in/blog/wp-content/uploads/2022/06/Shahi-Chicken-Biryani-01.jpg"
    },
    "butter chicken": {
        "history": "Invented in 1950s Delhi by Kundan Lal Gujral of Moti Mahal restaurant, who created the dish to use leftover tandoori chicken by simmering it in a rich tomato gravy with butter and cream.",
        "description": "Creamy tomato-based curry with tender tandoori chicken pieces",
        "ingredients": {
            "Chicken": ["500g chicken (boneless)", "1 cup yogurt", "2 tbsp tandoori masala"],
            "Gravy": ["4 tomatoes", "2 onions", "10 cashews (soaked)", "1 tbsp ginger-garlic paste"],
            "Spices": ["1 tsp garam masala", "1 tsp kasuri methi", "1/2 tsp turmeric"],
            "Dairy": ["2 tbsp butter", "1/2 cup fresh cream"]
        },
        "steps": [
            "Marinate chicken in yogurt and tandoori masala for 4 hours",
            "Grill or bake chicken until slightly charred",
            "Blend tomatoes, onions, and cashews to smooth paste",
            "Cook paste with spices until oil separates",
            "Add grilled chicken and simmer for 10 minutes",
            "Finish with fresh cream, butter, and kasuri methi",
            "Serve hot with naan"
        ],
        "image_url": "https://www.cookwithmanali.com/wp-content/uploads/2020/01/Butter-Chicken.jpg"
    },
    "masala dosa": {
        "history": "Originating from Udupi temples in Karnataka, this fermented crepe became a staple South Indian breakfast. The fermentation process was developed to preserve batter in tropical climates, while the potato filling was added later during British rule.",
        "description": "Crispy fermented rice crepe stuffed with spiced potato filling",
        "ingredients": {
            "Dosa Batter": ["2 cups rice", "1/2 cup urad dal", "1/4 tsp fenugreek seeds", "Water as needed"],
            "Potato Filling": ["3 potatoes (boiled)", "1 onion (sliced)", "1 tsp mustard seeds", "2 green chilies"],
            "Others": ["Oil for cooking", "Coconut chutney", "Sambar"]
        },
        "steps": [
            "Soak rice and dal separately for 6 hours",
            "Grind to smooth batter and ferment overnight",
            "Prepare potato filling with onions and spices",
            "Spread thin layer of batter on hot tawa",
            "Drizzle oil and cook until crispy",
            "Add potato filling and fold dosa",
            "Serve with chutney and sambar"
        ],
        "image_url": "https://www.vegrecipesofindia.com/wp-content/uploads/2021/06/masala-dosa-1.jpg"
    },

    # Italian Cuisine
    "pizza margherita": {
        "history": "Created in 1889 by pizzaiolo Raffaele Esposito in Naples to honor Queen Margherita, with toppings representing Italy's colors: red (tomato), white (mozzarella), and green (basil).",
        "description": "Classic Neapolitan pizza with simple, fresh ingredients",
        "ingredients": {
            "Dough": ["4 cups flour", "1.5 cups water", "2 tsp yeast", "1 tsp salt"],
            "Toppings": ["1/2 cup tomato sauce", "200g fresh mozzarella", "Fresh basil leaves"],
            "Other": ["Olive oil", "Salt to taste"]
        },
        "steps": [
            "Knead dough and let rise for 24 hours",
            "Stretch by hand into thin round base",
            "Spread tomato sauce and torn mozzarella",
            "Bake at 485°F (250°C) for 90 seconds in wood-fired oven",
            "Garnish with fresh basil and olive oil"
        ],
        "image_url": "https://www.academiabarilla.com/wp-content/uploads/2015/10/pizza-margherita-classica.jpg"
    },

    # Japanese Cuisine
    "sushi": {
        "history": "Originated as fermented fish preserved in rice in Southeast Asia, evolving in Edo-period Tokyo as nigiri sushi. The modern form developed in 1820s when Hanaya Yohei began serving fresh fish on vinegared rice.",
        "description": "Vinegared rice combined with raw fish and other ingredients",
        "ingredients": {
            "Rice": ["2 cups sushi rice", "2.5 cups water", "1/4 cup rice vinegar"],
            "Fish": ["200g fresh salmon/tuna", "4 shrimp", "1 cucumber"],
            "Other": ["Nori seaweed sheets", "Wasabi", "Soy sauce"]
        },
        "steps": [
            "Wash rice until water runs clear",
            "Cook rice and mix with vinegar mixture",
            "Slice fish against grain into thin pieces",
            "For nigiri: shape rice and top with fish",
            "For maki: spread rice on nori, add fillings, and roll",
            "Serve with wasabi and soy sauce"
        ],
        "image_url": "https://www.justonecookbook.com/wp-content/uploads/2022/01/How-To-Make-Sushi-Rice-8297-I.jpg"
    },

    # Mexican Cuisine
    "tacos al pastor": {
        "history": "Developed in 1920s Mexico by Lebanese immigrants who adapted their shawarma technique using local ingredients. The vertical spit and pineapple are Mexican innovations.",
        "description": "Marinated pork cooked on vertical spit with pineapple",
        "ingredients": {
            "Meat": ["1kg pork shoulder", "1/2 pineapple"],
            "Marinade": ["3 guajillo chilies", "3 ancho chilies", "1/2 cup orange juice"],
            "Tortillas": ["16 corn tortillas"],
            "Toppings": ["Chopped onion", "Cilantro", "Lime wedges"]
        },
        "steps": [
            "Blend marinade ingredients and coat pork",
            "Layer meat and pineapple on vertical spit",
            "Grill until crispy and caramelized",
            "Slice thin and serve on warm tortillas",
            "Top with onions, cilantro, and lime"
        ],
        "image_url": "https://images.themodernproper.com/billowy-turkey/production/posts/2022/Tacos-Al-Pastor-8.jpg"
    },

    # Thai Cuisine
    "pad thai": {
        "history": "Created in 1930s Thailand as part of national campaign to reduce rice consumption during shortages. The dish combines Chinese stir-fry techniques with local flavors.",
        "description": "Stir-fried rice noodles with eggs, tofu, and tamarind sauce",
        "ingredients": {
            "Noodles": ["200g rice noodles", "Water for soaking"],
            "Protein": ["2 eggs", "100g tofu", "100g shrimp"],
            "Sauce": ["3 tbsp tamarind paste", "2 tbsp fish sauce", "1 tbsp palm sugar"],
            "Others": ["Bean sprouts", "Peanuts", "Lime wedges"]
        },
        "steps": [
            "Soak noodles until pliable but firm",
            "Make sauce by balancing sweet, sour, and salty",
            "Stir-fry eggs, tofu, and shrimp",
            "Add noodles and sauce, toss vigorously",
            "Garnish with bean sprouts, peanuts, and lime"
        ],
        "image_url": "https://www.recipetineats.com/wp-content/uploads/2020/01/Pad-Thai_9.jpg"
    },

    # French Cuisine
    "coq au vin": {
        "history": "Traditionally made with rooster (coq) in Burgundy wine, this dish dates back to ancient Gaul. Julia Child popularized it internationally in the 1960s.",
        "description": "Chicken braised in red wine with mushrooms and bacon",
        "ingredients": {
            "Chicken": ["1 whole chicken (cut)", "Salt and pepper"],
            "Braising": ["2 cups red wine", "1 cup chicken stock", "200g mushrooms"],
            "Aromatics": ["200g pearl onions", "100g bacon", "2 garlic cloves"]
        },
        "steps": [
            "Marinate chicken in wine overnight",
            "Brown chicken and bacon in pot",
            "Add aromatics and cook until soft",
            "Return chicken, add wine and stock",
            "Simmer covered for 1 hour",
            "Add mushrooms and cook 30 minutes more"
        ],
        "image_url": "https://www.savingdessert.com/wp-content/uploads/2019/02/Coq-au-Vin-9.jpg"
    }
}

# ======================
# 🖼️ IMAGE RECOGNITION
# ======================
def load_model():
    model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)
    model.eval()
    return model

model = load_model()

def preprocess_image(image):
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    return transform(image).unsqueeze(0)

def predict_food(image):
    try:
        # For demo purposes - returns random dish from our database
        return random.choice(list(WORLD_RECIPES.keys()))
    except:
        return None

# ======================
# 📝 RECIPE GENERATION
# ======================
def generate_recipe(dish_name):
    dish_name = dish_name.lower().strip()

    if dish_name in WORLD_RECIPES:
        return WORLD_RECIPES[dish_name]

    try:
        summary = wikipedia.summary(f"{dish_name} recipe", sentences=3)
        return {
            "history": "Traditional dish with cultural significance",
            "description": summary,
            "ingredients": {"General": ["See detailed recipe for complete ingredients"]},
            "steps": ["1. Prepare all ingredients", "2. Follow traditional cooking method", "3. Serve appropriately"],
            "image_url": None
        }
    except:
        return None

# ======================
# 🖥️ GRADIO INTERFACE
# ======================
def process_input(image, text_input):
    dish = None
    if image is not None:
        dish = predict_food(image)
    if not dish and text_input:
        dish = text_input.lower().strip()

    if not dish:
        return "❌ Please provide an image or dish name", None

    recipe = generate_recipe(dish)
    if not recipe:
        return f"❌ No recipe found for {dish}", None

    # Format ingredients with categories
    ingredients_text = ""
    for category, items in recipe['ingredients'].items():
        ingredients_text += f"\n🍴 {category}:\n" + "\n".join([f"• {item}" for item in items]) + "\n"

    text_output = f"""
    🌍 {dish.title()} 🌍

    📜 History: {recipe.get('history', 'Traditional dish with cultural significance')}

    {recipe['description']}

    🛒 Ingredients:
    {ingredients_text}

    👨‍🍳 Preparation:
    {chr(10).join([f'{i+1}. {step}' for i, step in enumerate(recipe['steps'])])}
    """

    img_output = None
    if recipe['image_url']:
        try:
            response = requests.get(recipe['image_url'], timeout=5)
            img_output = Image.open(BytesIO(response.content))
        except:
            pass

    return text_output, img_output

# Create interface
with gr.Blocks(title="Global Recipe Explorer") as app:
    gr.Markdown("# 🌍 Global Recipe Explorer")
    gr.Markdown("Upload food image OR type dish name to get authentic recipe with history")

    with gr.Row():
        with gr.Column():
            image_input = gr.Image(type="pil", label="📸 Upload Food Photo")
            text_input = gr.Textbox(label="⌨️ Or Type Dish Name (e.g., Biryani, Pizza, Sushi)")
            submit_btn = gr.Button("👩‍🍳 Get Recipe", variant="primary")

        with gr.Column():
            text_output = gr.Textbox(label="📜 Recipe with History", interactive=False)
            image_output = gr.Image(label="🖼️ Dish Image", interactive=False)

    submit_btn.click(
        fn=process_input,
        inputs=[image_input, text_input],
        outputs=[text_output, image_output]
    )

# Launch app
app.launch(share=True)